services:
  - type: web
    name: kraftveb-app
    env: python
    buildCommand: |
      pip install -r requirements.txt
      npm install --prefix kraftveb-frontend
      npm run build --prefix kraftveb-frontend
    startCommand: gunicorn KraftVeb.wsgi:application --bind 0.0.0.0:10000
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: KraftVeb.settings
      - key: PYTHON_VERSION
        value: 3.11